version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec puma -C config/puma.rb 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
