github:
  client_id: '(secret)'
  secret: '(secret)'

analytics:
  tracking_id: 'UA-xxxxx-x'

top_page_users_count: 21
index_page_users_count: 20

# localhost:3000を使う場合は、settings.local.ymlでオーバーライドしてください。
host_name: rubyist-connect.dev
